#### 内部类与外嵌类的关系
1. 内部类可以调用其外嵌类的方法和成员变量
2. 内部类中的类体不能声明类变量和类方法，外嵌类可以声明内部类对象作为外嵌类的成员
3. 其他类不能使用某个类的内部类声明对象
4. 内部类可以被修饰为static内部类，但是static内部类就不能操作外部类的实例成员变量和方法了
5. static内部类可以被其他类使用来创建对象
6. 非内部类不能是static类

#### 匿名类
1. 匿名类是一个子类
2. 匿名类可以继承父类的方法也可以重写父类的方法
3. 匿名类可以访问外嵌类的成员变量和方法，匿名类的类体中不能声明static成员变量和方法
4. 匿名类是一个子类，但没有类名，所以在使用匿名类创建对象时，要直接使用父类的构造方法
```java
public abstract class people {
    public abstract void speak();
}

public class student extends people {
    @Override
    public void speak() {
        System.out.println("student speak");
    }
}

public class show {
    void show(people show){
        show.speak();
    }
}

public class text1 {
    public static void main(String[] args) {
        show show=new show();
        show.show(new people() {
            @Override
            public void speak() {
                System.out.println("student shows show");
            }
        });

        show.show(new student());
    }
}

结果：
student shows show
student speak
```
#### 和接口有关的匿名类
1. 用接口名和一个类体创建一个匿名对象，该类体认为是实现了接口的类去掉堆类声明后的类体。
```java
public interface speakHello {
    void speak();
}

public class helloText {
    public void turn(speakHello speakHello){
        speakHello.speak();
    }
}

public class text2 {
    public static void main(String[] args) {
        helloText helloText=new helloText();
        helloText.turn(new speakHello() {
            @Override
            public void speak() {
                System.out.println("speak hellp");
            }
        });

        helloText.turn(new speakHello() {
            @Override
            public void speak() {
                System.out.println("speak hellp hellp");
            }
        });
    }
}

result:
speak hellp
speak hellp hellp

#### 异常类
1. 使用try-catch语句
2. 自定义异常类
3. 如果try中语句发生异常，则转向catch中，发生异常后的语句不执行
4. 无论是否发生异常，finally中的语句均要执行用try-catch语句
```java
public class text3 {
    public static void main(String[] args) {
        int n=0,m=0,t=1000;
        try{
            m=Integer.parseInt("8888");
            n=Integer.parseInt("ab323");
            t=Integer.parseInt("2103");
        }catch (NumberFormatException e){
            System.out.println("发生异常"+e.getMessage());
        }

        System.out.println("m="+m+",n="+n+"t="+t);
    }
}

result:
发生异常For input string: "ab323"
m=8888,n=0t=1000
```
可以看出在n赋值发生异常后，转向了catch语句，t将不能再赋值，所以t仍等于原来的值

##### 自定义异常
throws和throw是两个不同的关键字，throws在方法声明时使用，throw用于抛出异常
```java
public class bankException  extends Exception{
    String message;
    public bankException(int m,int n){
        message="入账资金+"+m+"负数或支出"+n+"是正数，错误";
    }

    public String warnMessge(){
        return message;
    }
}


public class bank {
    private int money;
    public void income(int in,int out) throws bankException{
        if(in<=0||out>=0||in+out<=0){
            throw new bankException(in,out);
        }
        int come=in+out;
        System.out.println("本次纯收入"+come);
        money=money+come;
    }

    public int getMoney(){
        return money;
    }
}

public class text {
    public static void main(String[] args) {
        bank bank=new bank();
        try {
            bank.income(200,-100);
            bank.income(300,-100);
            System.out.println("当前账户有"+bank.getMoney());
            bank.income(200,100);
            bank.income(300,-100);
        } catch (bankException e) {
            System.out.println(e.warnMessge());
        }
        System.out.println("当前账户有"+bank.getMoney());

    }
}

result:
本次纯收入100
本次纯收入200
当前账户有300
入账资金+200负数或支出100是正数，错误
当前账户有300
```
#### 断言
1. 断言语句一般用于程序不准备通过捕获异常来处理错误，而是当发生错误时，程序立即停止运行
2. 语法格式
```java
assert booleanException
assert booleanException:messageException
```
3. assert number>=0,number>=0则返回true，程序继续执行，否则程序立刻结束执行
4. assert booleanException:messageException：当booleanException值为true时，程序从断言语句处继续执行，否则则停止执行，并输出messageException的值，提醒用户出现了怎么样的错误
